Vagrant.configure("2") do |config|

  config.vm.box_version = "1.0.0"
  config.vm.provider :vmware_desktop do |v|
    v.gui = true
    v.cpus = 2
    v.memory = 512
    v.vmx["ethernet0.virtualdev"] = "vmxnet3"
    v.ssh_info_public = true
    v.linked_clone = false
  end

  config.vm.define "dbserver" do |db|
    db.vm.box = "spox/ubuntu-arm"
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "10.10.10.10"
    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.groups = {
      "db" => ["dbserver"],
      "db:vars" => {"mongo_bind_ip" => "0.0.0.0"}
      }
    end
  end

  config.vm.define "appserver" do |app|
    app.vm.box = "spox/ubuntu-arm"
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "10.10.10.20"
    app.vm.provision "ansible" do |ansible|
     ansible.playbook = "playbooks/site.yml"
     ansible.groups = {
     "app" => ["appserver"],
     "app:vars" => { "db_host" => "10.10.10.10"}
     }
     end
  end

end
