---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: vmware
platforms:
  - name: instance
    box: "spox/ubuntu-arm"
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  scenario:
    name: default
verifier:
  name: ansible
